jobs:
  lint:
    ...

  test:
    ...

  build:
    ...

  deploy:
    needs: build
    uses: ./.github/workflows/reusable.yml
    with:
      artifact-name: dist-files

  print-deploy-result:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Output deploy result
        run: echo "Deploy result: ${{ needs.deploy.outputs.result }}"

  report:
    needs: [lint, deploy]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "Something went wrong"
          echo '${{ toJson(github) }}'
